HW2 is completed
jmequai/otus-golang pull request #2
Opened 2023-12-14 21:09 UTC by jmequai

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-16 14:58 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако есть критические замечания
Итого: 6 баллов из 10. Возвращаю задачу на доработку.

2023-12-16 14:58 UTC, agneum commented on .golangci.yml
> +#    - depguard
В решении не допускается отключать линтеры для успешного статуса пайплайна

2023-12-16 14:58 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	re := regexp.MustCompile(`(?s)(?:(?:\\.[0-9]?)|(?:.[0-9]?))`)
Регулярное выражение компилируется при каждом вызове функции, хотя его содержимое остаётся неизменным

2023-12-16 14:58 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	var escape, multiplier int = 0, -1
Почему для флага `escape` используется тип `int`?

2023-12-16 14:58 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	if escape == 0 && symbol >= 48 && symbol <= 57 {
Не очевидно, с какими именно значениями сравнивается значения символа

2023-12-16 14:58 UTC, agneum commented on hw02_unpack_string/unpack.go
> +				panic(e)
Крайне нежелательно, чтобы функция, особенно в библиотеке, паниковала.
Рекомендую обработать ошибочную ситуацию

2023-12-16 14:58 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	if multiplier >= 0 {
Почему используется сравнение `>=`?

2023-12-16 14:58 UTC, agneum commented on hw02_unpack_string/unpack.go
> +func Unpack(s string) (str string, err error) {
Решение выглядит немного переусложнённо с точки зрения поддержки, и, вероятно, получается не самое оптимальное по производительности.

Предложил бы подумать в сторону итерации по строке и стейт-машины.

2023-12-17 19:10 UTC, jmequai commented on hw02_unpack_string/unpack.go
> +func Unpack(s string) (str string, err error) {
Переделал на решение без регулярных выражений.

2023-12-18 06:45 UTC, agneum approved these changes
Спасибо за правки. 10/10. Принято

2023-12-19 12:21 UTC, merged